networks:
  default: development
  development:
    timeout: 120
    cmd_settings:
      accounts: 1
      mnemonic: brownie
      fork: https://optimism-mainnet.wallet.coinbase.com
      evm_version: shanghai
